florinp_messenger_index:
    path: /messenger
    defaults: { _controller: florinp.messenger.controller:index }
    
florinp_messenger_publish:
    path: /messenger/publish
    defaults: { _controller: florinp.messenger.controller:publish }
    
florinp_messenger_load:
    path: /messenger/load
    defaults: { _controller: florinp.messenger.controller:load }

florinp_messenger_update_messages:
    path: /messenger/update_messages
    defaults: { _controller: florinp.messenger.controller:updateMessages }
    
florinp_messenger_check_new_messages:
    path: /messenger/check_new_messages
    defaults: { _controller: florinp.messenger.controller:checkForNewMessages }