imports:
    - { resource: database.yml }
    - { resource: tables.yml  }
services:
    florinp.messenger.controller:
        class: florinp\messenger\controller\main
        arguments:
            - @request
            - @user
            - @florinp.messenger.model
            - @notification_manager
            - @florinp.messenger.libs.emojione
            - @florinp.messenger.libs.upload
            - @florinp.messenger.libs.download

    florinp.messenger.friends.controller:
        class: florinp\messenger\controller\friends
        arguments:
            - @config
            - @controller.helper
            - @template
            - @request
            - @user
            - @user_loader
            - @florinp.messenger.model.friends
            - @notification_manager

    florinp.messenger.listener:
        class: florinp\messenger\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @florinp.messenger.model
            - @florinp.messenger.model.friends
            - @user
            - @symfony_request
        tags:
            - { name: event.listener }

    florinp.messenger.model:
        class: florinp\messenger\models\main_model
        arguments:
            - @config
            - @controller.helper
            - @dbal.conn
            - @user
            - @florinp.messenger.libs.database
            - @florinp.messenger.libs.emojione
            - %florinp.messenger.tables.friends_request%
            - %florinp.messenger.tables.user_friends%

    florinp.messenger.model.friends:
        class: florinp\messenger\models\friends_model
        arguments:
          - @config
          - @controller.helper
          - @dbal.conn
          - @user
          - %florinp.messenger.tables.friends_request%
          - %florinp.messenger.tables.user_friends%

    florinp.messenger.libs.database:
        class: florinp\messenger\libs\database

    florinp.messenger.libs.emojione:
        class: florinp\messenger\libs\emojione

    florinp.messenger.libs.upload:
        class: florinp\messenger\libs\upload
        arguments:
            - %core.root_path%

    florinp.messenger.libs.download:
        class: florinp\messenger\libs\download
        arguments:
            - %core.root_path%

    florinp.messenger.notification.type.friend_request:
        class: florinp\messenger\notification\type\friend_request
        scope: prototype
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }
